component: scf
name: wxpayBedCareOrder
inputs:
  handler: index.main
  description: "20250613 "
  runtime: Nodejs18.15
  memorySize: 512
  installDependency: true
  timeout: 20
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: ""
  eip: false
  publicAccess: true
