component: scf
name: updateUserProfile
inputs:
  handler: index.main
  description: 个人信息编辑页，修改头像和昵称。
  runtime: Nodejs18.15
  memorySize: 256
  installDependency: true
  timeout: 20
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: ""
  eip: false
  publicAccess: true
