component: scf
name: listHospitals
inputs:
  handler: index.main
  description: 20250608，首页第一次使用
  runtime: Nodejs18.15
  memorySize: 256
  installDependency: true
  timeout: 20
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: ""
  eip: false
  publicAccess: true
